name: continuous-integration/gh-actions/cli

on: [push, pull_request]

jobs:
  build-linux-glibc-2-29:
    env:
      ZMQ_VERSION: v4.3.1
      CPPZMQ_VERSION: v4.3.0
      CFLAGS: -fPIC
      CXXFLAGS: -fPIC
      USE_SINGLE_BUILDDIR: 1
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: Install Haven dependencies
      run: |
        sudo apt update
        sudo apt-get --no-install-recommends --yes install libcurl4-openssl-dev build-essential cmake pkg-config libboost-all-dev libssl-dev libunbound-dev libsodium-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libpgm-dev libudev-dev
    - name: Install libzmq
      run: |
        git clone https://github.com/zeromq/libzmq.git -b ${ZMQ_VERSION}
        cd libzmq
        ./autogen.sh
        ./configure --enable-static --disable-shared
        make -j3
        sudo make install
        sudo ldconfig
    - name: Install cppzmq
      run: |
        git clone https://github.com/zeromq/cppzmq.git -b ${CPPZMQ_VERSION}
        cd cppzmq
        sudo mv *.hpp /usr/local/include
    - name: build Haven
      run: |
        make release-static -j3
        chmod +x build/release/bin/*
    - name: build haven explorer
      run: |
        cd haven-blockchain-explorer
        ./build-block-explorer.sh -j3
    - name: Upload Haven
      uses: actions/upload-artifact@v2
      with:
        name: Haven-Linux-x64 (glibc 2.29)
        path: build/release/bin/
    - name: Upload Haven Explorer
      uses: actions/upload-artifact@v2
      with:
        name: Haven-Explorer-Linux-x64 (glibc 2.29)
        path: |
          haven-blockchain-explorer/onion-monero-blockchain-explorer/build/xmrblocks
          haven-blockchain-explorer/onion-monero-blockchain-explorer/build/templates
  build-linux-glibc-2-27:
    env:
      ZMQ_VERSION: v4.3.1
      CPPZMQ_VERSION: v4.3.0
      CFLAGS: -fPIC
      CXXFLAGS: -fPIC
      USE_SINGLE_BUILDDIR: 1
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: Install Haven dependencies
      run: |
        sudo apt update
        sudo apt-get --no-install-recommends --yes install build-essential cmake pkg-config libboost-all-dev libssl-dev libunbound-dev libsodium-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libpgm-dev libudev-dev
    - name: Install libzmq
      run: |
        git clone https://github.com/zeromq/libzmq.git -b ${ZMQ_VERSION}
        cd libzmq
        ./autogen.sh
        ./configure --enable-static --disable-shared
        make -j3
        sudo make install
        sudo ldconfig
    - name: Install cppzmq
      run: |
        git clone https://github.com/zeromq/cppzmq.git -b ${CPPZMQ_VERSION}
        cd cppzmq
        sudo mv *.hpp /usr/local/include
    - name: build Haven
      run: |
        make release-static -j3
        chmod +x build/release/bin/*
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Haven-Linux-x64 (glibc 2.27)
        path: build/release/bin/
  build-macos:
    env:
      CMAKE_OSX_DEPLOYMENT_TARGET: 10.14
      OSX_MIN_VERSION: 10.14
      USE_SINGLE_BUILDDIR: 1
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install dependencies
      run: brew install hidapi zmq libpgm miniupnpc ldns expat libunwind-headers protobuf
    - name: build boost
      run: |
        wget https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz
        tar -xzf boost_1_71_0.tar.gz
        cd boost_1_71_0
        ./bootstrap.sh 
        ./b2
        ./b2 install
    - name: build
      run: |
        make release -j3
        chmod +x build/release/bin/*
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Haven-MacOS-10.14-and-later
        path: build/release/bin/
  build-windows:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: eine/setup-msys2@v0
      with:
        update: true
    - name: Install Haven dependencies
      run: msys2do pacman -S --noconfirm mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-libusb git patch
    - name: install boost
      run: |
        msys2do wget http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-boost-1.72.0-3-any.pkg.tar.zst
        msys2do wget http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-icu-66.1-1-any.pkg.tar.zst
        msys2do pacman -U --noconfirm *.tar.zst
    - name: build Haven
      run: msys2do make release-static-win64
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Haven-Windows-x64
        path: build/release/bin/
